services:
  portfolio:
    build:
      context: .
      args:
        - NEXT_PUBLIC_CV_URL=${NEXT_PUBLIC_CV_URL}
        - NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=${NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}
        - NEXT_PUBLIC_EMAILJS_SERVICE_ID=${NEXT_PUBLIC_EMAILJS_SERVICE_ID}
        - NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=${NEXT_PUBLIC_EMAILJS_TEMPLATE_ID}
    container_name: portfolio_nextjs
    restart: always
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production